import { useCallback, useEffect, useMemo, useState } from "react";
import confetti from "canvas-confetti";
import { toast } from "sonner";
import * as api from "./api";
import { Leaderboard } from "./components/Leaderboard";
import { Lobby } from "./components/Lobby";
import { LoginPanel } from "./components/LoginPanel";
import { PlayersPanel } from "./components/PlayersPanel";
import { QuestionCard } from "./components/QuestionCard";
import type { Question, Room, RoomState, ScoreEntry, User } from "./types";
import "./styles.css";
const getStoredUser = (): User | null => { try { return JSON.parse(localStorage.getItem("user") || "null"); } catch { return null; } };
export default function App() {
  const [user, setUser] = useState<User | null>(getStoredUser()); const [room, setRoom] = useState<Room | null>(null); const [question, setQuestion] = useState<Question | null>(null); const [leaderboard, setLeaderboard] = useState<ScoreEntry[]>([]); const [roomState, setRoomState] = useState<RoomState | null>(null); const [answeredQuestionIds, setAnsweredQuestionIds] = useState<Set<string>>(new Set()); const [currentUserAnswered, setCurrentUserAnswered] = useState(false); const [selectedOption, setSelectedOption] = useState<string>(); const [loadingAction, setLoadingAction] = useState<string | null>(null);
  const hasRoom = Boolean(room?.id);
  const refreshLeaderboard = useCallback(() => { if (!room?.id) return; api.getLeaderboard(room.id, 10).then((r) => setLeaderboard(r.entries)).catch(() => {}); }, [room?.id]);
  const refreshRoomState = useCallback(async () => { if (!room?.id) return; const r = await api.getRoomState(room.id, question?.id); setRoomState(r); if (r.room) setRoom(r.room); const p = r.players.find((x: any) => x.userId === user?.id); setCurrentUserAnswered(p?.answeredCurrentQuestion ?? false); }, [room?.id, question?.id, user?.id]);
  useEffect(() => { if (!room?.id) return; refreshLeaderboard(); refreshRoomState(); const i=setInterval(()=>{refreshLeaderboard(); refreshRoomState();},2000); return ()=>clearInterval(i); }, [room?.id, refreshLeaderboard, refreshRoomState]);
  const handleUser=(u:User)=>{setUser(u); localStorage.setItem("user",JSON.stringify(u)); toast.success("Sesión iniciada");};
  const handleGenerateQuestion=async()=>{ if(!room?.id) return; if(question && !roomState?.allAnswered){ toast.error("Aun faltan jugadores por responder"); return; } setLoadingAction("question"); try{ const r=await api.generateQuestion(room.id); setQuestion(r.question); setAnsweredQuestionIds(new Set()); setCurrentUserAnswered(false); setSelectedOption(undefined); await refreshRoomState(); toast.success("Pregunta generada"); } finally{ setLoadingAction(null);} };
  const handleAnswer=async(option:string)=>{ if(!room?.id||!user?.id||!question?.id) return; if(currentUserAnswered||answeredQuestionIds.has(question.id)){ toast.error("Ya respondiste esta pregunta"); return;} setLoadingAction("answer"); setSelectedOption(option); try{ const r=await api.submitAnswer(room.id,user.id,question.id,option,question.correctOption); if(r.correct){confetti({particleCount:100,spread:70,origin:{y:0.7}}); toast.success(`+${r.pointsAwarded ?? 100} puntos`);} else toast.error("Respuesta incorrecta"); setAnsweredQuestionIds((prev)=>new Set(prev).add(question.id)); setCurrentUserAnswered(true); await refreshLeaderboard(); await refreshRoomState(); }catch(e){ const m=e instanceof Error?e.message:"No se pudo enviar la respuesta"; if(m.includes("already answered")||m.includes("412")){ toast.error("Ya respondiste esta pregunta"); setAnsweredQuestionIds((prev)=>new Set(prev).add(question.id)); setCurrentUserAnswered(true); await refreshRoomState(); } else toast.error(m);} finally{ setLoadingAction(null);} };
  const playerNames = useMemo(() => { const map: Record<string,string> = {}; roomState?.players.forEach((p)=> map[p.userId]=p.username||p.userId.slice(0,8)); if(user?.id) map[user.id]=user.username; return map; }, [roomState,user]);
  return <main className="arena-shell">{!user ? <section className="arena-card auth-card"><LoginPanel onUser={handleUser} /></section> : <><section className="arena-card lobby-card"><div className="section-header"><h2>Sala de juego</h2><div className="room-badge"><span>Conectado al Gateway</span><strong>{room?.id ?? "Sin sala"}</strong>{room?.id && <button className="ghost-button" onClick={()=>navigator.clipboard.writeText(room.id).then(()=>toast.success("Codigo de sala copiado"))}>Copiar codigo</button>}</div></div><p className="muted">{room?.status==="WAITING"?"Esperando jugadores":room?.status==="STARTED"?"Partida en curso":room?.status==="FINISHED"?"Partida finalizada":""}</p><Lobby user={user} onRoom={setRoom} room={room} onRefreshRoomState={refreshRoomState} /></section>{hasRoom && <section className="action-bar"><button className="primary-button" disabled={!!loadingAction || (!!question && roomState?.allAnswered===false)} onClick={handleGenerateQuestion}>{loadingAction==="question"?"Generando...":"Generar pregunta"}</button></section>}<section className="arena-grid"><div className="arena-card question-section">{question ? <><QuestionCard question={question} onAnswer={handleAnswer} disabled={loadingAction==="answer" || currentUserAnswered} selectedOption={selectedOption} correctOption={question.correctOption} answered={currentUserAnswered} />{question && !roomState?.allAnswered && <p className="muted">Esperando respuestas de los demas jugadores...</p>}{question && roomState?.allAnswered && <p className="muted">Todos respondieron. Puedes generar la siguiente pregunta.</p>}</> : <div className="empty-state"><h2>Sin pregunta activa</h2></div>}</div><div className="arena-card leaderboard-section"><Leaderboard entries={leaderboard} onRefresh={refreshLeaderboard} playerNames={playerNames} /><PlayersPanel roomState={roomState} currentUserId={user.id} /></div></section></>}</main>;
}
